import type { SetupStage } from '@/shared/ui/SetupStageBadge';
import type { TradeDirection } from '@/shared/ui/DirectionBadge';

export type HistoryResult = 'successful' | 'failed' | 'expired' | 'invalidated' | 'unknown';
export type HistorySetupType = 'breakout' | 'bounce';

export interface MarketHistoryItem {
  id: string;
  setupId: string;
  replayId: string | null;
  symbol: string;
  exchange: 'BINANCE';
  timeframe: '1m' | '5m' | '15m';
  direction: TradeDirection;
  setupType: HistorySetupType;
  setupLabel: string;
  stageAtDetection: Exclude<SetupStage, 'triggered'>;
  detectedAt: string;
  completedAt: string | null;
  result: HistoryResult;
  resultLabel: string;
  detectedPrice: number;
  levelZone: string;
  maxMovePct: number | null;
  adverseMovePct: number | null;
  timeToTargetSec: number | null;
  formationDurationSec: number;
  touchesCount: number;
  pullbackLabel: 'Глубокие' | 'Неглубокие' | '—';
  btcRelativeStrength: number | null;
  resultReason: string;
  resultNote: string;
  replayAvailable: boolean;
  chartPoints: number[];
}

export const HISTORY_RESULT_LABELS: Record<HistoryResult, string> = {
  successful: 'Успешный',
  failed: 'Неудачный',
  expired: 'Истёк',
  invalidated: 'Отменён',
  unknown: 'Без результата',
};

export const MARKET_HISTORY_ITEMS: MarketHistoryItem[] = [
  {
    id: 'history-001',
    setupId: 'setup-sol-18742',
    replayId: 'replay-sol-18742',
    symbol: 'SOLUSDT',
    exchange: 'BINANCE',
    timeframe: '5m',
    direction: 'long',
    setupType: 'breakout',
    setupLabel: 'Пробой сопротивления',
    stageAtDetection: 'confirmation',
    detectedAt: '2026-07-15T14:18:00Z',
    completedAt: '2026-07-15T14:36:00Z',
    result: 'successful',
    resultLabel: 'Пробой',
    detectedPrice: 187.42,
    levelZone: '188.10–188.42',
    maxMovePct: 3.84,
    adverseMovePct: -0.32,
    timeToTargetSec: 1080,
    formationDurationSec: 8280,
    touchesCount: 3,
    pullbackLabel: 'Неглубокие',
    btcRelativeStrength: 2.7,
    resultReason: 'Цена закрепилась выше зоны сопротивления после усиления потока покупок.',
    resultNote: 'После пробоя импульс продолжился без глубокого возврата в зону.',
    replayAvailable: true,
    chartPoints: [18, 22, 20, 28, 31, 29, 38, 43, 41, 48, 52, 58, 55, 64, 69, 75, 82, 88],
  },
  {
    id: 'history-002',
    setupId: 'setup-arb-0752',
    replayId: 'replay-arb-0752',
    symbol: 'ARBUSDT',
    exchange: 'BINANCE',
    timeframe: '1m',
    direction: 'long',
    setupType: 'breakout',
    setupLabel: 'Пробой сопротивления',
    stageAtDetection: 'approach',
    detectedAt: '2026-07-15T12:42:00Z',
    completedAt: '2026-07-15T12:50:00Z',
    result: 'successful',
    resultLabel: 'Пробой',
    detectedPrice: 0.7498,
    levelZone: '0.7501–0.7520',
    maxMovePct: 2.16,
    adverseMovePct: -0.21,
    timeToTargetSec: 480,
    formationDurationSec: 2880,
    touchesCount: 3,
    pullbackLabel: 'Неглубокие',
    btcRelativeStrength: 1.4,
    resultReason: 'Третий подход к уровню прошёл на ускорении сделок и росте объёма.',
    resultNote: 'Пробой реализовался быстро, основное движение сформировалось за восемь минут.',
    replayAvailable: true,
    chartPoints: [25, 27, 31, 30, 36, 39, 37, 44, 48, 47, 57, 63, 71, 78, 84, 89],
  },
  {
    id: 'history-003',
    setupId: 'setup-op-1603',
    replayId: 'replay-op-1603',
    symbol: 'OPUSDT',
    exchange: 'BINANCE',
    timeframe: '5m',
    direction: 'short',
    setupType: 'breakout',
    setupLabel: 'Пробой поддержки',
    stageAtDetection: 'confirmation',
    detectedAt: '2026-07-15T11:09:00Z',
    completedAt: '2026-07-15T11:40:00Z',
    result: 'successful',
    resultLabel: 'Пробой',
    detectedPrice: 1.607,
    levelZone: '1.603–1.612',
    maxMovePct: 2.42,
    adverseMovePct: -0.37,
    timeToTargetSec: 1860,
    formationDurationSec: 12720,
    touchesCount: 3,
    pullbackLabel: 'Неглубокие',
    btcRelativeStrength: -1.9,
    resultReason: 'Поддержка не удержала повторное давление продавцов.',
    resultNote: 'После закрепления ниже зоны цена продолжила снижение на растущем объёме.',
    replayAvailable: true,
    chartPoints: [84, 81, 78, 80, 72, 68, 70, 63, 59, 55, 58, 49, 44, 39, 32, 27, 20],
  },
  {
    id: 'history-004',
    setupId: 'setup-eth-3506',
    replayId: 'replay-eth-3506',
    symbol: 'ETHUSDT',
    exchange: 'BINANCE',
    timeframe: '15m',
    direction: 'long',
    setupType: 'bounce',
    setupLabel: 'Отскок от поддержки',
    stageAtDetection: 'approach',
    detectedAt: '2026-07-15T09:30:00Z',
    completedAt: '2026-07-15T10:15:00Z',
    result: 'successful',
    resultLabel: 'Отскок',
    detectedPrice: 3498.4,
    levelZone: '3 492–3 506',
    maxMovePct: 1.72,
    adverseMovePct: -0.18,
    timeToTargetSec: 2700,
    formationDurationSec: 20520,
    touchesCount: 2,
    pullbackLabel: 'Глубокие',
    btcRelativeStrength: 0.8,
    resultReason: 'В зоне поддержки появилась последовательная реакция покупателей.',
    resultNote: 'Цена не обновила локальный минимум и дошла до следующего внутридневного уровня.',
    replayAvailable: true,
    chartPoints: [67, 62, 58, 51, 44, 38, 34, 36, 43, 49, 54, 61, 65, 72, 78, 82],
  },
  {
    id: 'history-005',
    setupId: 'setup-apt-0716',
    replayId: 'replay-apt-0716',
    symbol: 'APTUSDT',
    exchange: 'BINANCE',
    timeframe: '5m',
    direction: 'short',
    setupType: 'breakout',
    setupLabel: 'Пробой поддержки',
    stageAtDetection: 'confirmation',
    detectedAt: '2026-07-14T18:22:00Z',
    completedAt: '2026-07-14T18:49:00Z',
    result: 'failed',
    resultLabel: 'Ложный пробой',
    detectedPrice: 7.14,
    levelZone: '7.12–7.16',
    maxMovePct: 0.36,
    adverseMovePct: -1.21,
    timeToTargetSec: null,
    formationDurationSec: 11340,
    touchesCount: 3,
    pullbackLabel: 'Неглубокие',
    btcRelativeStrength: -0.7,
    resultReason: 'Цена вышла ниже зоны, но продавцы не смогли удержать ускорение.',
    resultNote: 'Произошёл быстрый возврат за уровень с ростом агрессивных покупок.',
    replayAvailable: true,
    chartPoints: [73, 69, 66, 61, 58, 51, 45, 39, 34, 29, 25, 31, 43, 56, 68, 77],
  },
  {
    id: 'history-006',
    setupId: 'setup-link-1696',
    replayId: 'replay-link-1696',
    symbol: 'LINKUSDT',
    exchange: 'BINANCE',
    timeframe: '5m',
    direction: 'long',
    setupType: 'breakout',
    setupLabel: 'Пробой сопротивления',
    stageAtDetection: 'approach',
    detectedAt: '2026-07-14T15:07:00Z',
    completedAt: '2026-07-14T16:02:00Z',
    result: 'failed',
    resultLabel: 'Уровень удержан',
    detectedPrice: 16.88,
    levelZone: '16.91–16.96',
    maxMovePct: 0.28,
    adverseMovePct: -1.08,
    timeToTargetSec: null,
    formationDurationSec: 5760,
    touchesCount: 3,
    pullbackLabel: 'Неглубокие',
    btcRelativeStrength: 0.4,
    resultReason: 'Покупатели подошли к уровню без достаточного роста активности.',
    resultNote: 'После касания продавцы вернули цену в предыдущий диапазон.',
    replayAvailable: true,
    chartPoints: [28, 32, 37, 41, 47, 52, 58, 63, 68, 72, 74, 69, 60, 51, 43, 37],
  },
  {
    id: 'history-007',
    setupId: 'setup-xrp-0622',
    replayId: null,
    symbol: 'XRPUSDT',
    exchange: 'BINANCE',
    timeframe: '15m',
    direction: 'short',
    setupType: 'bounce',
    setupLabel: 'Отскок от сопротивления',
    stageAtDetection: 'observation',
    detectedAt: '2026-07-14T12:00:00Z',
    completedAt: '2026-07-14T14:24:00Z',
    result: 'expired',
    resultLabel: 'Время истекло',
    detectedPrice: 0.6241,
    levelZone: '0.6290–0.6320',
    maxMovePct: null,
    adverseMovePct: null,
    timeToTargetSec: null,
    formationDurationSec: 26640,
    touchesCount: 2,
    pullbackLabel: 'Глубокие',
    btcRelativeStrength: -0.2,
    resultReason: 'Цена не вернулась к зоне в пределах рабочего окна сетапа.',
    resultNote: 'Ситуация перестала быть актуальной без реализации и без нарушения уровня.',
    replayAvailable: false,
    chartPoints: [56, 54, 57, 53, 55, 58, 56, 54, 57, 55, 56, 53, 55, 54, 56, 55],
  },
  {
    id: 'history-008',
    setupId: 'setup-doge-0144',
    replayId: 'replay-doge-0144',
    symbol: 'DOGEUSDT',
    exchange: 'BINANCE',
    timeframe: '1m',
    direction: 'short',
    setupType: 'bounce',
    setupLabel: 'Отскок от сопротивления',
    stageAtDetection: 'approach',
    detectedAt: '2026-07-14T10:16:00Z',
    completedAt: '2026-07-14T10:52:00Z',
    result: 'invalidated',
    resultLabel: 'Уровень снят',
    detectedPrice: 0.1439,
    levelZone: '0.1441–0.1448',
    maxMovePct: null,
    adverseMovePct: -0.64,
    timeToTargetSec: null,
    formationDurationSec: 2160,
    touchesCount: 2,
    pullbackLabel: 'Глубокие',
    btcRelativeStrength: -0.6,
    resultReason: 'Зона сопротивления потеряла силу после расширения диапазона.',
    resultNote: 'NEXUS отменил сетап до появления подтверждения, вход не рассматривался.',
    replayAvailable: true,
    chartPoints: [42, 45, 49, 52, 55, 59, 62, 67, 72, 76, 73, 69, 65, 61, 58, 56],
  },
  {
    id: 'history-009',
    setupId: 'setup-inj-2804',
    replayId: 'replay-inj-2804',
    symbol: 'INJUSDT',
    exchange: 'BINANCE',
    timeframe: '1m',
    direction: 'long',
    setupType: 'breakout',
    setupLabel: 'Пробой сопротивления',
    stageAtDetection: 'confirmation',
    detectedAt: '2026-07-13T21:34:00Z',
    completedAt: '2026-07-13T21:46:00Z',
    result: 'successful',
    resultLabel: 'Пробой',
    detectedPrice: 27.98,
    levelZone: '27.92–28.04',
    maxMovePct: 4.18,
    adverseMovePct: -0.41,
    timeToTargetSec: 720,
    formationDurationSec: 4320,
    touchesCount: 3,
    pullbackLabel: 'Неглубокие',
    btcRelativeStrength: 3.1,
    resultReason: 'Высокая относительная сила к BTC совпала с пробоем локального диапазона.',
    resultNote: 'Самый сильный сетап выборки: движение реализовалось быстро и без возврата.',
    replayAvailable: true,
    chartPoints: [17, 21, 25, 23, 29, 34, 38, 45, 49, 55, 61, 68, 74, 81, 88, 93],
  },
  {
    id: 'history-010',
    setupId: 'setup-sui-298',
    replayId: null,
    symbol: 'SUIUSDT',
    exchange: 'BINANCE',
    timeframe: '5m',
    direction: 'long',
    setupType: 'bounce',
    setupLabel: 'Отскок от поддержки',
    stageAtDetection: 'observation',
    detectedAt: '2026-07-13T16:05:00Z',
    completedAt: '2026-07-13T18:12:00Z',
    result: 'expired',
    resultLabel: 'Время истекло',
    detectedPrice: 2.94,
    levelZone: '2.88–2.91',
    maxMovePct: null,
    adverseMovePct: null,
    timeToTargetSec: null,
    formationDurationSec: 10800,
    touchesCount: 2,
    pullbackLabel: 'Глубокие',
    btcRelativeStrength: 0.1,
    resultReason: 'Цена продолжила боковое движение выше зоны и не дала рабочего входа.',
    resultNote: 'Сетап закрыт по времени, рыночная структура осталась нейтральной.',
    replayAvailable: false,
    chartPoints: [48, 51, 49, 52, 54, 50, 53, 55, 52, 54, 51, 53, 52, 55, 54, 53],
  },
  {
    id: 'history-011',
    setupId: 'setup-avax-267',
    replayId: 'replay-avax-267',
    symbol: 'AVAXUSDT',
    exchange: 'BINANCE',
    timeframe: '15m',
    direction: 'short',
    setupType: 'breakout',
    setupLabel: 'Пробой поддержки',
    stageAtDetection: 'approach',
    detectedAt: '2026-07-13T11:45:00Z',
    completedAt: '2026-07-13T13:20:00Z',
    result: 'invalidated',
    resultLabel: 'Структура изменилась',
    detectedPrice: 26.82,
    levelZone: '26.65–26.78',
    maxMovePct: null,
    adverseMovePct: -0.52,
    timeToTargetSec: null,
    formationDurationSec: 19800,
    touchesCount: 2,
    pullbackLabel: 'Глубокие',
    btcRelativeStrength: -0.4,
    resultReason: 'Новый локальный минимум сформировал другую рабочую зону.',
    resultNote: 'Старый уровень исключён из наблюдения до потенциального входа.',
    replayAvailable: true,
    chartPoints: [68, 64, 60, 57, 53, 49, 45, 48, 52, 55, 58, 61, 59, 62, 64, 66],
  },
  {
    id: 'history-012',
    setupId: 'setup-bnb-715',
    replayId: 'replay-bnb-715',
    symbol: 'BNBUSDT',
    exchange: 'BINANCE',
    timeframe: '5m',
    direction: 'long',
    setupType: 'bounce',
    setupLabel: 'Отскок от поддержки',
    stageAtDetection: 'confirmation',
    detectedAt: '2026-07-12T19:12:00Z',
    completedAt: '2026-07-12T20:05:00Z',
    result: 'failed',
    resultLabel: 'Поддержка пробита',
    detectedPrice: 714.8,
    levelZone: '711.5–714.0',
    maxMovePct: 0.44,
    adverseMovePct: -1.53,
    timeToTargetSec: null,
    formationDurationSec: 15120,
    touchesCount: 3,
    pullbackLabel: 'Глубокие',
    btcRelativeStrength: 0.5,
    resultReason: 'Первая реакция покупателей не получила продолжения.',
    resultNote: 'После короткого отскока продавцы пробили поддержку и закрепились ниже.',
    replayAvailable: true,
    chartPoints: [55, 49, 43, 37, 32, 29, 34, 42, 48, 51, 46, 39, 31, 24, 19, 15],
  },
];
